name: Trigger auto deployment for conapp03

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/conapp03-AutoDeployTrigger-1c6a6412-854d-471e-a029-d330c90a8dfc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONAPP03_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONAPP03_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONAPP03_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: uatacr001.azurecr.io
          registryUsername: ${{ secrets.CONAPP03_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONAPP03_REGISTRY_PASSWORD }}
          containerAppName: conapp03
          resourceGroup: rg-uat-conapp
          imageToBuild: uatacr001.azurecr.io/conapp03:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


